import { ReactNode, useContext, useState } from 'react'
import { Button, Space } from 'antd'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import PublicLayout from '@/components/layouts/PublicLayout'
import { MyLectures } from '@/components/MyLectures'
import { TonContext } from '@/contexts/ton-context'
import styles from '@/styles/Home.module.css'

const AddLectureModal = dynamic(() => import('@/components/modals/AddLectureModal').then((r) => r.AddLectureModal), { ssr: false })

const MyLecturesPage = ({ user }: any) => {
	const { connector } = useContext(TonContext)
	const [addLectureModalOpen, setAddLectureModalOpen] = useState(false)
	const [lectureAdded, setLectureAdded] = useState(false)

	const handleAddLecture = () => {
		setAddLectureModalOpen(false)
		setLectureAdded(true)
	}

	return (
		<>
			<Head>
				<title>{process.env.APP_NAME}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				{connector?.connected && (
					<>
						<Space direction="vertical" style={{ width: '100%' }}>
							<Button onClick={() => setAddLectureModalOpen(true)}>Создать платную лекцию</Button>
							<MyLectures forceUpdate={lectureAdded} onUpdate={() => setLectureAdded(false)} />
						</Space>

						<AddLectureModal open={addLectureModalOpen} onFinish={handleAddLecture} onCancel={() => setAddLectureModalOpen(false)} />
					</>
				)}
			</main>
		</>
	)
}

MyLecturesPage.getLayout = (page: ReactNode) => <PublicLayout>{page}</PublicLayout>

export default MyLecturesPage
