import { ReactElement, useContext, useState } from 'react'
import PublicLayout from '@/components/layouts/PublicLayout'
import { LecturesList } from '@/components/LecturesList'
import styles from '@/styles/Home.module.css'
import { Space, Typography } from 'antd'
import Head from 'next/head'
import { ReadyLecturesList } from '@/components/ReadyLecturesList'

const { Title, Text } = Typography

const Home = () => {
	return (
		<>
			<Head>
				<title>{process.env.APP_NAME}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div className={styles.mainIntro}>
					<Title>Decentralized crowdfunding for lectures</Title>
					<Text type="secondary">Share knowledge with your community. This is a platform where you can find funding for interesting lectures</Text>
				</div>
				<Space direction="vertical" size="large" style={{ width: '100%' }}>
					<LecturesList />
					<br />
					<ReadyLecturesList />
				</Space>
			</main>
		</>
	)
}

Home.getLayout = (page: ReactElement) => <PublicLayout>{page}</PublicLayout>

export default Home
