import { ReactElement, useContext, useState } from 'react'
import PublicLayout from '@/components/layouts/PublicLayout'
import { LecturesList } from '@/components/LecturesList'
import { TonContext } from '@/services/ton/context'
import styles from '@/styles/Home.module.css'
import { Typography } from 'antd'
import Head from 'next/head'
// import dynamic from 'next/dynamic'

// const LectureModal = dynamic(() => import('@/components/modals/LectureModal').then((r) => r.LectureModal), { ssr: false })

const { Title, Text } = Typography

const Home = ({ user }: any) => {
	const { connector, userWallet } = useContext(TonContext)
	const [lectureModalOpen, setLectureModalOpen] = useState(false)

	// const handleAddLecture = () => {
	// 	setLectureModalOpen(false)
	// refetchLectures()
	// }

	return (
		<>
			<Head>
				<title>{process.env.APP_NAME}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div className={styles.mainIntro}>
					<Title>Decentralized crowdfunding for lectures</Title>
					<Text type="secondary">Share knowledge with your community. This is a platform where you can find funding for interesting lectures</Text>
				</div>
				<LecturesList />
			</main>

			{/* <LectureModal open={lectureModalOpen} onFinish={handleAddLecture} onCancel={() => setLectureModalOpen(false)} /> */}
		</>
	)
}

Home.getLayout = (page: ReactElement) => <PublicLayout>{page}</PublicLayout>

export default Home
