import { ReactElement, useContext, useState } from 'react'
import PublicLayout from '@/components/layouts/PublicLayout'
import { LecturesList } from '@/components/LecturesList'
import { TonContext } from '@/services/ton/context'
import styles from '@/styles/Home.module.css'
import { Typography } from 'antd'
// import dynamic from 'next/dynamic'
import Head from 'next/head'

// const AddLectureModal = dynamic(() => import('@/components/modals/AddLectureModal').then((r) => r.AddLectureModal), { ssr: false })

const { Title, Text } = Typography

const Home = ({ user }: any) => {
	const { connector, userWallet } = useContext(TonContext)
	const [addLectureModalOpen, setAddLectureModalOpen] = useState(false)

	// const handleAddLecture = () => {
	// 	setAddLectureModalOpen(false)
	// refetchLectures()
	// }

	return (
		<>
			<Head>
				<title>{process.env.APP_NAME}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				{/* <Button onClick={() => setAddLectureModalOpen(true)}>Создать платную лекцию</Button> */}
				<div className={styles.mainIntro}>
					<Title>Do or fund lectures</Title>
					<Text type="secondary">Share lectures for everyone. This is a platform where you can find funding for interesting lectures</Text>
				</div>
				<LecturesList />
			</main>

			{/* <AddLectureModal open={addLectureModalOpen} onFinish={handleAddLecture} onCancel={() => setAddLectureModalOpen(false)} /> */}
		</>
	)
}

Home.getLayout = (page: ReactElement) => <PublicLayout>{page}</PublicLayout>

export default Home
